//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Resources/GameController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace MUGCUP
{
    public partial class @GameController : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @GameController()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameController"",
    ""maps"": [
        {
            ""name"": ""SlotSelection"",
            ""id"": ""0ddd7281-2673-4343-8d79-a779afb92401"",
            ""actions"": [
                {
                    ""name"": ""MoveUp"",
                    ""type"": ""Button"",
                    ""id"": ""830451ef-55e7-44f0-96de-1c28386d5be0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveDown"",
                    ""type"": ""Button"",
                    ""id"": ""96dd7f48-967d-447b-b6d7-cc65954ac4ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveRight"",
                    ""type"": ""Button"",
                    ""id"": ""5d79afc3-35ec-49f8-908d-40737927549d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveLeft"",
                    ""type"": ""Button"",
                    ""id"": ""dea1e138-7d8e-4ba7-b3c8-110ff65b5a38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlideLeft"",
                    ""type"": ""Button"",
                    ""id"": ""0a241e89-b6a7-4270-9cff-3eadc2d47b5d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlideRight"",
                    ""type"": ""Button"",
                    ""id"": ""2cf6f7e5-2933-4891-9e9e-777cc7bd773b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlideUp"",
                    ""type"": ""Button"",
                    ""id"": ""5a1c7e4c-f45a-4bbe-a949-667ee85c0059"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlideDown"",
                    ""type"": ""Button"",
                    ""id"": ""92074958-5f7f-440c-b615-8f158a9b297c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""38a9c620-cc06-425a-98d3-4902de709910"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7e889b2-3ad4-4348-961c-96fc23b8be06"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""636e8ea4-3d58-45de-b5b6-a0a09a328af0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bd0da64-0464-460f-a164-7e7dfa55f32b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ebae5d44-430a-4136-9bf4-52014216ab21"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlideLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46038e25-6a8a-4226-8781-35abf017d200"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlideRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c385709-01fd-4a46-9c99-10a22469cc45"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlideUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78ebda3d-6e94-4a58-b438-88a91c160ae8"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlideDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ItemSelection"",
            ""id"": ""4d76f874-0833-4a68-a555-42c844aaa3e9"",
            ""actions"": [
                {
                    ""name"": ""UseSlot_1st"",
                    ""type"": ""Button"",
                    ""id"": ""7cae45aa-e6da-4d3f-b28d-f008edf21c1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseSlot_2nd"",
                    ""type"": ""Button"",
                    ""id"": ""2bca6a79-56ea-40f6-b3a0-842ae4428096"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseSlot_3rd"",
                    ""type"": ""Button"",
                    ""id"": ""75ac5792-d386-4ef2-b2a4-2fa638de4e14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseSlot_4st"",
                    ""type"": ""Button"",
                    ""id"": ""0a4b1ee7-b5e8-47a4-b254-e8dfb2a7c4be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseSlot_5st"",
                    ""type"": ""Button"",
                    ""id"": ""bae37fc4-35e9-4384-a052-aa789758523a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""96597797-4d81-4dce-90b4-dad476f53a61"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSlot_1st"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d221fb12-0989-434e-b48c-464d5e39730f"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSlot_2nd"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b699d4ac-f11f-4ef3-8e8b-df95d0824d97"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSlot_3rd"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b1ca33b-31fb-4679-9b9a-5d939cc13fff"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSlot_4st"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6075bca-2a39-44b9-b50f-4b30e4382964"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSlot_5st"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // SlotSelection
            m_SlotSelection = asset.FindActionMap("SlotSelection", throwIfNotFound: true);
            m_SlotSelection_MoveUp = m_SlotSelection.FindAction("MoveUp", throwIfNotFound: true);
            m_SlotSelection_MoveDown = m_SlotSelection.FindAction("MoveDown", throwIfNotFound: true);
            m_SlotSelection_MoveRight = m_SlotSelection.FindAction("MoveRight", throwIfNotFound: true);
            m_SlotSelection_MoveLeft = m_SlotSelection.FindAction("MoveLeft", throwIfNotFound: true);
            m_SlotSelection_SlideLeft = m_SlotSelection.FindAction("SlideLeft", throwIfNotFound: true);
            m_SlotSelection_SlideRight = m_SlotSelection.FindAction("SlideRight", throwIfNotFound: true);
            m_SlotSelection_SlideUp = m_SlotSelection.FindAction("SlideUp", throwIfNotFound: true);
            m_SlotSelection_SlideDown = m_SlotSelection.FindAction("SlideDown", throwIfNotFound: true);
            // ItemSelection
            m_ItemSelection = asset.FindActionMap("ItemSelection", throwIfNotFound: true);
            m_ItemSelection_UseSlot_1st = m_ItemSelection.FindAction("UseSlot_1st", throwIfNotFound: true);
            m_ItemSelection_UseSlot_2nd = m_ItemSelection.FindAction("UseSlot_2nd", throwIfNotFound: true);
            m_ItemSelection_UseSlot_3rd = m_ItemSelection.FindAction("UseSlot_3rd", throwIfNotFound: true);
            m_ItemSelection_UseSlot_4st = m_ItemSelection.FindAction("UseSlot_4st", throwIfNotFound: true);
            m_ItemSelection_UseSlot_5st = m_ItemSelection.FindAction("UseSlot_5st", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // SlotSelection
        private readonly InputActionMap m_SlotSelection;
        private ISlotSelectionActions m_SlotSelectionActionsCallbackInterface;
        private readonly InputAction m_SlotSelection_MoveUp;
        private readonly InputAction m_SlotSelection_MoveDown;
        private readonly InputAction m_SlotSelection_MoveRight;
        private readonly InputAction m_SlotSelection_MoveLeft;
        private readonly InputAction m_SlotSelection_SlideLeft;
        private readonly InputAction m_SlotSelection_SlideRight;
        private readonly InputAction m_SlotSelection_SlideUp;
        private readonly InputAction m_SlotSelection_SlideDown;
        public struct SlotSelectionActions
        {
            private @GameController m_Wrapper;
            public SlotSelectionActions(@GameController wrapper) { m_Wrapper = wrapper; }
            public InputAction @MoveUp => m_Wrapper.m_SlotSelection_MoveUp;
            public InputAction @MoveDown => m_Wrapper.m_SlotSelection_MoveDown;
            public InputAction @MoveRight => m_Wrapper.m_SlotSelection_MoveRight;
            public InputAction @MoveLeft => m_Wrapper.m_SlotSelection_MoveLeft;
            public InputAction @SlideLeft => m_Wrapper.m_SlotSelection_SlideLeft;
            public InputAction @SlideRight => m_Wrapper.m_SlotSelection_SlideRight;
            public InputAction @SlideUp => m_Wrapper.m_SlotSelection_SlideUp;
            public InputAction @SlideDown => m_Wrapper.m_SlotSelection_SlideDown;
            public InputActionMap Get() { return m_Wrapper.m_SlotSelection; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(SlotSelectionActions set) { return set.Get(); }
            public void SetCallbacks(ISlotSelectionActions instance)
            {
                if (m_Wrapper.m_SlotSelectionActionsCallbackInterface != null)
                {
                    @MoveUp.started -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnMoveUp;
                    @MoveUp.performed -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnMoveUp;
                    @MoveUp.canceled -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnMoveUp;
                    @MoveDown.started -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnMoveDown;
                    @MoveDown.performed -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnMoveDown;
                    @MoveDown.canceled -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnMoveDown;
                    @MoveRight.started -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnMoveRight;
                    @MoveRight.performed -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnMoveRight;
                    @MoveRight.canceled -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnMoveRight;
                    @MoveLeft.started -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnMoveLeft;
                    @MoveLeft.performed -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnMoveLeft;
                    @MoveLeft.canceled -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnMoveLeft;
                    @SlideLeft.started -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnSlideLeft;
                    @SlideLeft.performed -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnSlideLeft;
                    @SlideLeft.canceled -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnSlideLeft;
                    @SlideRight.started -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnSlideRight;
                    @SlideRight.performed -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnSlideRight;
                    @SlideRight.canceled -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnSlideRight;
                    @SlideUp.started -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnSlideUp;
                    @SlideUp.performed -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnSlideUp;
                    @SlideUp.canceled -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnSlideUp;
                    @SlideDown.started -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnSlideDown;
                    @SlideDown.performed -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnSlideDown;
                    @SlideDown.canceled -= m_Wrapper.m_SlotSelectionActionsCallbackInterface.OnSlideDown;
                }
                m_Wrapper.m_SlotSelectionActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @MoveUp.started += instance.OnMoveUp;
                    @MoveUp.performed += instance.OnMoveUp;
                    @MoveUp.canceled += instance.OnMoveUp;
                    @MoveDown.started += instance.OnMoveDown;
                    @MoveDown.performed += instance.OnMoveDown;
                    @MoveDown.canceled += instance.OnMoveDown;
                    @MoveRight.started += instance.OnMoveRight;
                    @MoveRight.performed += instance.OnMoveRight;
                    @MoveRight.canceled += instance.OnMoveRight;
                    @MoveLeft.started += instance.OnMoveLeft;
                    @MoveLeft.performed += instance.OnMoveLeft;
                    @MoveLeft.canceled += instance.OnMoveLeft;
                    @SlideLeft.started += instance.OnSlideLeft;
                    @SlideLeft.performed += instance.OnSlideLeft;
                    @SlideLeft.canceled += instance.OnSlideLeft;
                    @SlideRight.started += instance.OnSlideRight;
                    @SlideRight.performed += instance.OnSlideRight;
                    @SlideRight.canceled += instance.OnSlideRight;
                    @SlideUp.started += instance.OnSlideUp;
                    @SlideUp.performed += instance.OnSlideUp;
                    @SlideUp.canceled += instance.OnSlideUp;
                    @SlideDown.started += instance.OnSlideDown;
                    @SlideDown.performed += instance.OnSlideDown;
                    @SlideDown.canceled += instance.OnSlideDown;
                }
            }
        }
        public SlotSelectionActions @SlotSelection => new SlotSelectionActions(this);

        // ItemSelection
        private readonly InputActionMap m_ItemSelection;
        private IItemSelectionActions m_ItemSelectionActionsCallbackInterface;
        private readonly InputAction m_ItemSelection_UseSlot_1st;
        private readonly InputAction m_ItemSelection_UseSlot_2nd;
        private readonly InputAction m_ItemSelection_UseSlot_3rd;
        private readonly InputAction m_ItemSelection_UseSlot_4st;
        private readonly InputAction m_ItemSelection_UseSlot_5st;
        public struct ItemSelectionActions
        {
            private @GameController m_Wrapper;
            public ItemSelectionActions(@GameController wrapper) { m_Wrapper = wrapper; }
            public InputAction @UseSlot_1st => m_Wrapper.m_ItemSelection_UseSlot_1st;
            public InputAction @UseSlot_2nd => m_Wrapper.m_ItemSelection_UseSlot_2nd;
            public InputAction @UseSlot_3rd => m_Wrapper.m_ItemSelection_UseSlot_3rd;
            public InputAction @UseSlot_4st => m_Wrapper.m_ItemSelection_UseSlot_4st;
            public InputAction @UseSlot_5st => m_Wrapper.m_ItemSelection_UseSlot_5st;
            public InputActionMap Get() { return m_Wrapper.m_ItemSelection; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(ItemSelectionActions set) { return set.Get(); }
            public void SetCallbacks(IItemSelectionActions instance)
            {
                if (m_Wrapper.m_ItemSelectionActionsCallbackInterface != null)
                {
                    @UseSlot_1st.started -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_1st;
                    @UseSlot_1st.performed -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_1st;
                    @UseSlot_1st.canceled -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_1st;
                    @UseSlot_2nd.started -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_2nd;
                    @UseSlot_2nd.performed -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_2nd;
                    @UseSlot_2nd.canceled -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_2nd;
                    @UseSlot_3rd.started -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_3rd;
                    @UseSlot_3rd.performed -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_3rd;
                    @UseSlot_3rd.canceled -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_3rd;
                    @UseSlot_4st.started -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_4st;
                    @UseSlot_4st.performed -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_4st;
                    @UseSlot_4st.canceled -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_4st;
                    @UseSlot_5st.started -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_5st;
                    @UseSlot_5st.performed -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_5st;
                    @UseSlot_5st.canceled -= m_Wrapper.m_ItemSelectionActionsCallbackInterface.OnUseSlot_5st;
                }
                m_Wrapper.m_ItemSelectionActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @UseSlot_1st.started += instance.OnUseSlot_1st;
                    @UseSlot_1st.performed += instance.OnUseSlot_1st;
                    @UseSlot_1st.canceled += instance.OnUseSlot_1st;
                    @UseSlot_2nd.started += instance.OnUseSlot_2nd;
                    @UseSlot_2nd.performed += instance.OnUseSlot_2nd;
                    @UseSlot_2nd.canceled += instance.OnUseSlot_2nd;
                    @UseSlot_3rd.started += instance.OnUseSlot_3rd;
                    @UseSlot_3rd.performed += instance.OnUseSlot_3rd;
                    @UseSlot_3rd.canceled += instance.OnUseSlot_3rd;
                    @UseSlot_4st.started += instance.OnUseSlot_4st;
                    @UseSlot_4st.performed += instance.OnUseSlot_4st;
                    @UseSlot_4st.canceled += instance.OnUseSlot_4st;
                    @UseSlot_5st.started += instance.OnUseSlot_5st;
                    @UseSlot_5st.performed += instance.OnUseSlot_5st;
                    @UseSlot_5st.canceled += instance.OnUseSlot_5st;
                }
            }
        }
        public ItemSelectionActions @ItemSelection => new ItemSelectionActions(this);
        public interface ISlotSelectionActions
        {
            void OnMoveUp(InputAction.CallbackContext context);
            void OnMoveDown(InputAction.CallbackContext context);
            void OnMoveRight(InputAction.CallbackContext context);
            void OnMoveLeft(InputAction.CallbackContext context);
            void OnSlideLeft(InputAction.CallbackContext context);
            void OnSlideRight(InputAction.CallbackContext context);
            void OnSlideUp(InputAction.CallbackContext context);
            void OnSlideDown(InputAction.CallbackContext context);
        }
        public interface IItemSelectionActions
        {
            void OnUseSlot_1st(InputAction.CallbackContext context);
            void OnUseSlot_2nd(InputAction.CallbackContext context);
            void OnUseSlot_3rd(InputAction.CallbackContext context);
            void OnUseSlot_4st(InputAction.CallbackContext context);
            void OnUseSlot_5st(InputAction.CallbackContext context);
        }
    }
}
